### ISSUE TITLE
motivation for using github?

### ISSUE THREAD

**Issue by emjayess** [WindowsAzure/windowsazure.github.io#2]
I'm debating with a colleague the probable motivation(s) for using github over alternatives or msft mainstays (e.g. tfs), and am hoping the azure sdk team participating on these projects can help settle it.

So...

What was the primary motivation for using github for the open source sdk stuff?

**Comment by ghost** [comment]
Hi,
I just saw this issue on this page - and unfortunately these repos on GitHub just aren't the best place for random discussion. I would suggest trying Twitter or StackOverflow to engage a little better in this kind of conversation.

On the Windows Azure SDK team we've embraced GitHub because a lot of our open source work is in SDKs and runtimes that are very popular in the GitHub community - namely `node.js` - and so being here allows us to better fork and engage with Node users.

If you're looking for C#/.NET I'd say that CodePlex and/or TFS hosting is the very popular thing to do!

Thanks,
Jeff
